version: '3.4'

networks:
  quiz:
    driver: bridge


services:
  quiz-api:
    container_name: quizapi   
    build:
      context: .
      dockerfile: QuizSolution/Dockerfile
    ports:
      - 8000:8080
    depends_on:
      - quiz-db
    environment:
     - DB_HOST=quiz-db
     - DB_NAME=quizdb
     - DB_SA_PASSWORD=Pass@123
    networks:
      - quiz
    volumes:
      - logs:/quizlogs
  quiz-db:
        container_name: quizdb
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
         - 8002:1433
        environment:
          SA_PASSWORD: Pass@123
          ACCEPT_EULA: Y
        networks:
         - quiz
        volumes:
         - db-data:/var/opt/mssql
volumes:
  db-data:  
  logs: