version: "3.4"

services:
  quiz-api:
    container_name: quizapi
    build:
      context: .
    ports:
      - 8000:80
    env_file:
      - ./.env
    volumes:
      - logs:/quizlogs
volumes:
  logs:
