version: "3.4"

services:
  quiz-api:
    container_name: quizapi
    build:
      context: .
    ports:
      - 8000:80
    env_file:
      - ./.env
    volumes:
      - logs:/quizlogs
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  logs:
  redis_data:
