version: "3.4"

services:
  quiz-api:
    container_name: quizapi
    build:
      context: .
    ports:
      - 8000:80
    env_file:
      - ./.env
    volumes:
      - logs:/quizlogs
    depends_on:
      - redis
    networks:
      my_network:
        ipv4_address: 172.28.0.2

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      my_network:
        ipv4_address: 172.28.0.3

volumes:
  logs:
  redis_data:

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
